theme: minima

title: Avi Fishman
description: >
  Essays that I think are worth writing.
# Site behavior
show_excerpts: true


# Markdown & syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Feed & SEO
feed:
  path: atom.xml

# Navigation (top menu)
header_pages:
  - about.md

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Avi Fishman
      comments: false

# Permalinks (clean & essay-friendly)
permalink: /:categories/:title/

# Exclude dev files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules






